### ISSUE TITLE
Feat: Setup + Document `date` and `time` input in a `Flutter` App

### ISSUE THREAD

**Issue by nelsonic** [dwyl/flutter-date-time-tutorial#1]
As noted by @panoramix360 in https://github.com/dwyl/mvp/issues/140#issuecomment-1629885618 
the `MVP` currently has `text` `input` for updating the `timer.start` and `timer.stop`: 

<img width="657" alt="image" src="https://github.com/dwyl/flutter-date-time-tutorial/assets/194400/706409a1-a1d3-4394-9fa6-b0a83aaafb19">

# Todo

+ [x] Follow the instructions in the core [`Material`](https://api.flutter.dev/flutter/material/material-library.html) library to implement the [`DatePicker`](https://api.flutter.dev/flutter/material/DatePickerDialog-class.html) and [`TimePicker`](https://api.flutter.dev/flutter/material/TimePickerDialog-class.html) widgets and allow a `person` to interact with a [`DateTime`](https://api.flutter.dev/flutter/dart-core/DateTime-class.html) object. 

> **Note**: The data does not need to be persisted to a "backend"; just on the device is fine. 📱 
But if you want to get creative / use your imagination and make it a "guess the date game", that's fine too. 💭 

+ [ ] Once we've figured out the "basics" of the `Material UI` widgets, 
explore a more intuitive and _faster_ interface.
  ***Specifically*** we don't want a "[Modal](https://github.com/dwyl/product-ux-research/issues/38)" (Dialog) for inputting the `DateTime`. We want the `timers` input to expand below the `item` the way it currently does in the `MVP` so no context is lost.

+ [ ] Ensure the `App` is deployed via `GitHub Pages` as a `PWA`. 📱 

# Research

There are _many_ options available, e.g: https://fluttergems.dev/date-time-picker
<img width="1602" alt="image" src="https://github.com/dwyl/flutter-date-time-tutorial/assets/194400/0551aab9-80ea-43f9-874c-f695ceed516e">

Please feel free to do more research into this but remember to capture all of it.
And don't get _tooo_ carried away as this feature is meant to be simple. 👌

**Comment by nelsonic** [comment]
@LuchoTurtle please drop a comment in this thread when you are able to take a look at it. 🙏

**Comment by LuchoTurtle** [comment]
Just to understand correctly: I'm going to replicate a simple *local* todo app (the person creates todo items), where each one has a `start` datepicker and `end` datepicker, which they can edit. Adding a starting and stopping timer would add more complexity and would deviate from this repo's original purpose.

Is this correct? If so, I'll take this on after getting through other issues

**Comment by nelsonic** [comment]
No need for Todo `items`. Literally just display a _single_ `DateTime` on a page and allow them to update it. 📆 ⌚ 
This is a UI/UX quest and our objective is just to study the interface for inputting/updating the data. 📱

**Comment by LuchoTurtle** [comment]
Ok, I'll do that and showcase the values of the `DateTime` below (like `JSON.stringify`) just people can see the value change overtime.

**Comment by nelsonic** [comment]
Cool. What I was saying above about making it a Game that people play to "Guess the Date"
e.g: https://guess-the-date.com/party is _way_ beyond the scope / our needs:
<img width="1503" alt="image" src="https://github.com/dwyl/flutter-date-time-tutorial/assets/194400/bfee2227-2ed3-4b97-adb6-4f2f494eb80e">

But we can drop a hint to hit in the end of the tutorial. 👍

**Comment by nelsonic** [comment]
@LuchoTurtle is there enough detail in this issue for you to start work on it _tomorrow_? 🧑‍💻 📆 🤞

**Comment by LuchoTurtle** [comment]
@nelsonic As discussed on standup, I'll be finishing https://github.com/dwyl/dart_cid/issues/6#event-9730227216 since it was already in-progress last time I picked it up. After this, the package should have less "activity" since it should be "complete", in a sense.
I'll work on this issue after I'm done 👌

**Comment by nelsonic** [comment]
Cool. Agree with _finishing_ the work you started to [_free your mind_](https://www.youtube.com/watch?v=gmawiQsMJPc) from it. 😉 
But `this` issue/quest is definitely more `product`-focussed. 📱 :shipit: 👌 
Thanks. 🙏

**Comment by LuchoTurtle** [comment]
From my research and having looked at the link you've provided (https://fluttergems.dev/date-time-picker/), it seems that 99% of these date and time pickers *use modals*, which is funny, since in most cases, changing date and time are often found in [inline editing scenarios](https://news.ycombinator.com/item?id=36058029). 

An issue has been opened https://github.com/flutter/flutter/issues/76053 regarding this issue. Some people wanted to use the default Material `Date` and `TimePicker` widgets without a dialogue. It's been argued that it goes against ["Material guidelines"](https://github.com/flutter/flutter/issues/76053#issuecomment-947451422), so it seems it's gotten stale ever since.

There are a few candidates (e.g. https://morioh.com/a/f191fd917990/flutter-date-pickers-without-dialog). However, most use a ton of space and just print out the calendar, which is not desirable in our scenario: we don't want a calendar to be shown to the person, it takes too much real estate.

To fulfil the requirement of "No Modals 🚫", though, I have a question regarding mobile devices. Quite literally all of the pickers I've found make use of the "modal" or "pop-up" from native Android and iPhone.

![image](https://github.com/dwyl/flutter-date-time-tutorial/assets/17494745/34051de0-ad6f-4b6e-a10a-b1653f75d648)

Does this make sense on mobile devices? Should we go for the native approach or still be reluctant to use modals/dialogues/popups in mobile apps? Should we just avoid these in the web version?

I understand the value of not using modals. They can't be bookmarked or shared as links; they can't be opened in new tabs; they don't work well with the Back button. These are issues that occur on *browsers* but not necessarily on mobile apps. I get that changing the context is still an issue but given the screen constraint, does it make sense? 

I can continue searching but I haven't found well-supported projects that properly do inline date and timer editing. The only viable route that I'm aware of is using a `TextField` with form validation which follows a strict format.

**Comment by nelsonic** [comment]
@LuchoTurtle as discussed on our Standup call this morning, 📞 
our objective with this tutorial is to have something we can `use` in our `App` ASAP. 🏁 
Yes, sadly, the "standard" (`Material UI`) `Flutter` widgets are [`Modal`](https://github.com/dwyl/product-ux-research/issues/38). 🙄 
We can "setup" the project with these widgets to get up-and-running as quick as possible.
But then immediately inform the reader that `while` these are widely used in practice,
they are are _poor_ UX and we've seen older `people` get confused/frustrated with `Modals` in the past.
So we _prefer_ an "inline" approach every time.
Buuuutttt ... if we are _forced_ to use `Modal` to get the _first_ version shipped, we will.

Thank you for your research and linking to the issues it's good context for anyone `else` reading this in the future. 👌

**Comment by LuchoTurtle** [comment]
@nelsonic yes, I understand what you are saying. I understand that using modals, especially in web browsers, is a no-go.
I was just wondering about pop-ups like those found in native iPhones. For example:

![image](https://github.com/dwyl/flutter-date-time-tutorial/assets/17494745/e73becd4-389a-495a-bf82-2e5c396f9548)

Are these *a problem*? Because even if we were to go through inlining, a keyboard would be shown as well in the same area of the popup. So why not show the popup like this instead?
Hence why I was wondering if there was a clear difference between **web browsers** and **mobile apps**.

Thanks for answering 👌

**Comment by nelsonic** [comment]
Sadly, 20-something hipster designers in San Francisco have made `Modals` _normal_...
The `iPhone` has plenty of horrible `UX` and poor in-app feature discovery. There was a thread on this just yesterday: https://news.ycombinator.com/item?id=36846520

The "scrolling" input for dates and times is not great interface design,
but being `Native` it means people are _already_ familiar with it.
Which means we can (reluctantly) use it and people will _understand_ it. 

We need to maintain a consistent interface across devices and experiences. 
As soon as the `Flutter` App has feature-parity with the `MVP` it will _become_ the `App` and we will no longer _need_ the `MVP`.

**Comment by LuchoTurtle** [comment]
I've created a draft PR #2 which will address this issue.
I've already have implemented and documented a demo with both `timePicker`, `datePicker` separately and together, as well.
I've tried finding solutions that would be inlining and I couldn't found what I was looking for. It seems likely that the only way to go is to use a `TextField` that is formatted and is validated as the person inputs, following a given `regex`. 
This is peculiar, because using `Material`'s pickers have an "input mode":

<img width="538" alt="image" src="https://github.com/dwyl/flutter-date-time-tutorial/assets/17494745/c3263c04-b08e-427e-9ab8-7108835a594b">

Which does exactly what we want to do: a `TextField`-like input where one can type the wanted date and get instant feedback (except that we don't want a modal).

<img width="504" alt="image" src="https://github.com/dwyl/flutter-date-time-tutorial/assets/17494745/c1696b21-3b1c-4f03-929d-7e2ca15f1f29">

I might have to take a look into the source code on this one 🤔

**Comment by LuchoTurtle** [comment]
Time also has an input mode, which is fully typable.

<img width="468" alt="image" src="https://github.com/dwyl/flutter-date-time-tutorial/assets/17494745/1c2798c6-ce26-4154-b58a-6c420dc7f75c">

From https://github.com/flutter/flutter/issues/76053, I wish they offered an option to *not* use this as a modal.

**Comment by nelsonic** [comment]
Can the time input be 24h instead of “AM/PM” to reduce clutter?

**Comment by LuchoTurtle** [comment]
> Can the time input be 24h instead of “AM/PM” to reduce clutter?

I think we can, using [`MediaQuery`](https://api.flutter.dev/flutter/widgets/MediaQuery-class.html) we can force military time via localization.

**Comment by LuchoTurtle** [comment]
I'll probably reduce the scope of this to just demoing `Flutter` Material and Cupertino components, with possibility to keep track of changes, and testing them.
The reason is that there is no discernable way of actually not *easily* using a Modal that doesn't take me less than a handful of hours of research, scouring through source code and *trying* to replicate this behaviour "modal-less" (see https://stackoverflow.com/questions/69513759/can-i-possibly-always-display-the-this-timepicker-widget). 
We're not alone on this (https://github.com/flutter/flutter/issues/76053).

**Comment by nelsonic** [comment]
Today I had to book an Uber car. The interface for scheduling pickup uses Cupertino but it's _not_ a modal/dialog:

![IMG_4655](https://github.com/dwyl/flutter-date-time-tutorial/assets/194400/3e30d196-cf5d-42dc-8a98-0544e9a2122f)

Most likely it's a `Swift` / `Objective C`.
